# docker-compose.yml

version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; sleep 5; uvicorn app.main:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=user-manager
      - POSTGRES_PASSWORD=user-manager
      - POSTGRES_DB=user-manager
      - POSTGRES_PORT=5432
    depends_on:
      - db
    #env_file:
    #  - ./.env
    networks:
      - practice
    links:
      - db

  db:
    image: 'postgres'
    restart: always
    volumes:
      - db:/var/lib/postgresql/data/
    #  - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - '5432:5432'
    #expose:
    #  - 5432
    environment:
      - POSTGRES_USER=user-manager
      - POSTGRES_PASSWORD=user-manager
      - POSTGRES_DB=user-manager
    networks:
      - practice

volumes:
  db:
    driver: local

networks:
  practice: